services:
   xeyes:
      image: "carlomt/xeyes"
      stdin_open: true 
      tty: true
         
   gears:
      image: "carlomt/gears"
      stdin_open: true 
      tty: true   
      privileged: true     
   geant4:
      # user: $(id -u):$(id -g)
      image: "carlomt/geant4course"
      stdin_open: true 
      tty: true   
      volumes:
         - ./geant4-datasets/:/opt/geant4/data/:ro
         - ./geant4-source/:/usr/local/geant4/
         - ./docker-home/:/root/
         - ./geant4-exercises/:/root/geant4-exercises/
      working_dir: /root
      # depends_on:
      #    data-downloader:
      #      condition: service_completed_successfully
   prepare:
      image: "carlomt/geant4course"
      command: >
        /bin/bash -c "
        /opt/geant4/bin/geant4-config --install-datasets && 
        /usr/bin/curl https://geant4-data.web.cern.ch/geant4-data/releases/source/geant4-v$$(/opt/geant4/bin/geant4-config --version).tar.gz --output /usr/local/geant4/geant4.tar.gz &&
        /usr/bin/tar -xvf /usr/local/geant4/geant4.tar.gz -C /usr/local/geant4/ &&
        rm /usr/local/geant4/geant4.tar.gz &&
        echo 'We suggest you to work on exercises in this folder' > /root/geant4-exercises/README &&
        echo 'This folder will be mapped as your home (/root) in the container' > /root/README
        "
      stdin_open: true    
      tty: true      
      volumes:
         - ./geant4-datasets/:/opt/geant4/data/
         - ./geant4-source/:/usr/local/geant4/
         - ./docker-home/:/root/
         - ./geant4-exercises/:/root/geant4-exercises/
   test:
      image: "carlomt/geant4course"
      stdin_open: true 
      tty: true    
      volumes:
         - ./geant4-datasets/:/opt/geant4/data/:ro
         - ./geant4-source/:/usr/local/geant4/
         - ./docker-home/:/root/
         - ./geant4-exercises/:/root/geant4-exercises/
      working_dir: /root
      command: >
        /bin/bash -c "
        cp -r /usr/local/geant4/geant4-v$$(/opt/geant4/bin/geant4-config --version)/examples/basic/B4/B4a/ /root/geant4-exercises/ &&
        mkdir -p /root/geant4-exercises/B4a-build &&
        cd /root/geant4-exercises/B4a-build && cmake /root/geant4-exercises/B4a &&
        cd /root/geant4-exercises/B4a-build && make -j$$(nproc) &&
        cd /root/geant4-exercises/B4a-build && ./exampleB4a
        "
   root:
      image: "rootproject/root:6.26.14-ubuntu20.04"
      stdin_open: true 
      tty: true              
      entrypoint: ["/usr/bin/bash", "-l"]
      volumes:        
         - ./docker-home:/root
         - ./geant4-exercises:/root/geant4-exercises                  
      working_dir: /root
volumes:
  geant4-datasets:
     external: true
  geant4-source:
     external: true
  geant4-exercises:
     external: true
  docker-home:
     external: true
  

